### ISSUE TITLE
Websocket termination

### ISSUE THREAD

**Issue by andrzejszymeczek** [gilmaimon/ArduinoWebsockets#106]
Hi, 
I'm having a trouble solving one issue on my side. I'm using websocket client for ESP32.My ESP32 chip connects to webapp via WS and then there is a data exchange. At the end of my work I want to end the session just by plugging off power supply of ESP. However ws on server side is showing that ws client is still active. I thought that when one side of ws dies the other side gets info about that. 

Do you have any idea what should i try?

**Comment by olegsavelos** [comment]
That is how sockets work, you will need to send PING messages from your server at lower time periods so it could detect a disconnected client.

**Comment by gilmaimon** [comment]
@olegsavelos gave you a great answer :) Closing until you'll have anything else to ask
