### ISSUE TITLE
WebsocketsEvent returns only GotPing event

### ISSUE THREAD

**Issue by akc4** [gilmaimon/ArduinoWebsockets#122]
using this example : https://github.com/gilmaimon/ArduinoWebsockets/blob/master/examples/Minimal-Esp32-Client/Minimal-Esp32-Client.ino

The only callback that I get is the `WebsocketsEvent::GotPing` event.

I trigger custom events and see them in my `pusher` debug console, is it possible to catch custom events?

**Comment by gilmaimon** [comment]
It's odd that you don't see a connection opened event.. Custom events are not supported, but I'm sure it will be easy to implement if you'll follow the `WebsocketsEvent` enum and it's usage :)

**Comment by akc4** [comment]
@gilmaimon thank you for your reply, 

I see the first `connection_established` with the `WebsocketsMessage` callback. Then after that the only callback I get is the `GotPing` from `WebsocketsEvent`.

I am absolutely new to arduino/c++, how would I implement a custom event listener, on my hand the event is called `Order` and it simply returns an object. Or if you could guide me to some documentation that would put me on the right path.

Thanks
