### ISSUE TITLE
How to handle disconnect or an error

### ISSUE THREAD

**Issue by johneakin** [gilmaimon/ArduinoWebsockets#13]
What is the best way to reconnect after a disconnect or some error?

I tried the following but doesn't appear to be working.
void onEventsCallback(WebsocketsEvent event, String data) {
   if(event == WebsocketsEvent::ConnectionClosed) {
         client.connect("wss://ws-feed.pro.coinbase.com");
         client.send("{\"type\": \"subscribe\",\"product_ids\": [\"BTC-USD\"],\"channels\": [\"ticker\"]}");
}

Instead is there any way to check if the connection is active in the loop() and reconnect from there?

**Comment by gilmaimon** [comment]
Hi, the best way to check if a client is connected is by using:
```c++
if (client.available()) {
   // Connected...
}
```

The best way to reconnect is to reset the object (by assinging a new instance) and setting up the callbacks again. So for example:

```c++
if (client.available()) {
   // Connected, do something...
} else {
    client = WebsocketsClient();
    client.onMessage(...);
    client.onEvent(...);
    client.connect(...);
}
```

**Comment by gilmaimon** [comment]
I consider this issue resolved. If you have any other queshtions please share, otherwise I will close this issue due to inactivity.

**Comment by gilmaimon** [comment]
Resolved.

**Comment by alldone** [comment]
> Hi, the best way to check if a client is connected is by using:
> 
> ```c++
> if (client.available()) {
>    // Connected...
> }
> ```
> 
> The best way to reconnect is to reset the object (by assinging a new instance) and setting up the callbacks again. So for example:
> 
> ```c++
> if (client.available()) {
>    // Connected, do something...
> } else {
>     client = WebsocketsClient();
>     client.onMessage(...);
>     client.onEvent(...);
>     client.connect(...);
> }
> ```

this is what i was looking for ....... however it is an excellent library, a great job.
thank you
