### ISSUE TITLE
Can we get a documentation/wiki?

### ISSUE THREAD

**Issue by williamsokol** [gilmaimon/ArduinoWebsockets#133]
I am relatively new to websockets and using the esp products and am forced to go through the cpp manually and find out things like server.accept() is blocking.

It would be nice to have some sort of wiki or documentation where we can post about all the commands and how to use them.

It could at least help if there is a full list of all the commands in the ReadMe. 

I think it is possible to open wikis in GitHub but making one anywhere would help a lot.

**Comment by gilmaimon** [comment]
Did you read the README?

> Please check out the [TinyWebsockets Wiki](https://github.com/gilmaimon/TinyWebsockets/wiki)[](https://github.com/gilmaimon/ArduinoWebsockets#getting-started) for many more details!

It's slightly outdated, but has most of the basics covered.
