### ISSUE TITLE
ESP32 Websocket Client doesn't connect to Node.js Websocket server

### ISSUE THREAD

**Issue by j-eyking** [gilmaimon/ArduinoWebsockets#138]
Hi,

Cam someone point me in the right direction why an ESP32 set as Websocket client doesn't connect to a Node.js websocket server running on localhost?

I've tested server and client with another client respectively server, so I can rely on correct operation of both.

Puting in some logging in websockets_client.cpp learned that this->_connectionOpen of function WebsocketsClient::connect remains false.

**Comment by bluecoder15** [comment]
I am using wss connection. I println the client.connect(websockets_connection_string) , it shows 0. 

Note: The readme section mentioned for SSL on esp32, we can provide full certificate or provide no certificate. Hence, I didn't provide the cert because I am using esp32

**Comment by j-eyking** [comment]
> Hi The issue is related to your computer firewall Go to firewall settings and set the inbound rule to accept all connections on the port your server is running on.

You're right. I've checked firewall settings before posting, but I was not aware of the fact that in Windows my wireless network is set as public network. The fact checkboxes of Node.js were checked only for a private network didn't ring a bell because of that.
