### ISSUE TITLE
poll() disconnects client

### ISSUE THREAD

**Issue by the-powl** [gilmaimon/ArduinoWebsockets#139]
I'm trying to call poll() in a loop for checking on incoming connections and if true create a WebsocketsClient named client. As soon as a client is connected though, it gets disconnected again when the loop rolls over and reaches if(server.poll()) again. I found out via placing Serial.println() commands in between every step. If I never call poll() again, the client never disonnects.

I'm using it on an ESP8266. Library version is 0.5.3. Websocket connection is established via a simple html/js document, which does not initiate the disconnect on its own.

Here's a minimized code:
```
void loop() {
  static WebsocketsClient client;
 
  if(server.poll()) {
    client = server.accept();
    Serial.println("new client!");
  }

  if(client.available()) {
    WebsocketsMessage msg = client.readBlocking();

    // log
    Serial.print("Got Message: ");
    Serial.println(msg.data());

    // return echo
    client.send("Echo: " + msg.data());
    Serial.println("Echo: " + msg.data());
  }

  delay(1000);
}
```

Am I doing something wrong?

**Comment by zastrixarundell** [comment]
Haven't use this library in a long time but:

You are polling again which is fine but if it's true you again accept the connection, that would be an issue, no? 

What happens when you only poll it, does it disconnect again?

**Comment by the-powl** [comment]
After accepting the first connection, the result of poll() is false, as expected, so therefore the if block doesn't get executed. Nevertheless the client gets disconnected.

**Comment by zastrixarundell** [comment]
Okay, you're connecting first, then you are reading the message in a blocking manner and then you additionally wait one second. I don't see you sending a heartbeat to the server so maybe the server doesn't recognize you as connected anymore? I know that I had an issue like that and I was sending a heartbeat connection every second or so. 

I used lambdas to receive messages from the client without actually stopping the main loop. Here's the directory with both my declaration and implementation if that helps: https://github.com/zastrixarundell/phomenix/tree/master/arduino/lib/PhoenixConnection

**Comment by the-powl** [comment]
Unfortunately I'm not sure how to send a heartbeat and I don't just want to send random garbage. Shouldn't the TCP connection be maintained by the library itself or by an underlying level? Interestingly I can also wait more than 1 second... like 5 or even 10. The client gets only disconnected as soon as I call poll() again.

**Comment by zastrixarundell** [comment]
No, heartbeats need to be sent manually because heartbeats depend on the
technology the server uses. On my server it was Elixir/Phoenix so I had to
send heartbeats specifically for that.

Can you try a basic websocket server maybe via python? I don't know the
cause of this issue.

**Comment by the-powl** [comment]
omg I'm stupid. I oversaw a websocket.close() in my partly copy and pasted javascript code which was responsible for closing the connection. I got suspicious when I tried to use another library. Thanks for help!
