### ISSUE TITLE
Esp32 WebSocket Client won't work with WebSocket Node.js server.

### ISSUE THREAD

**Issue by seifirobotic** [gilmaimon/ArduinoWebsockets#153]
the esp32 client example does not work with a server on Node.js, but if I used postman to connect to the server it connects without any troubles.

The Arduino ide serial monitor:

![Screenshot 2024-04-02 112537](https://github.com/gilmaimon/ArduinoWebsockets/assets/163295034/986168f0-4983-42d6-8525-1bd7641f4f88)

The WebSocket server code:

![Screenshot 2024-04-02 112519](https://github.com/gilmaimon/ArduinoWebsockets/assets/163295034/9cadb3aa-03b8-486e-ace4-5a05407b11d6)

Postman connected to the server:

![Screenshot 2024-04-02 113129](https://github.com/gilmaimon/ArduinoWebsockets/assets/163295034/a9947f0a-6436-4670-978f-b881bf54546d)

server receiving message from Postman: 

![Screenshot 2024-04-02 113114](https://github.com/gilmaimon/ArduinoWebsockets/assets/163295034/07790544-dacc-4abb-89c3-84f9a079a392)

Note: I did not change anything in the library while trying this.

**Comment by yogibagus** [comment]
Hii, i have the same problem? do you know how to fix it? can you tell me right here?
i'd be appreciated if you do. thanks.

**Comment by seifirobotic** [comment]
this would help.
https://stackoverflow.com/a/72324727
