### ISSUE TITLE
Set custom headers on WSS connection

### ISSUE THREAD

**Issue by mmcArg** [gilmaimon/ArduinoWebsockets#22]
Hi!!!, first of all, the library is great!!!!, and sorry for my english.
I am working with a server that requires a token in connection header ("Authorization: JWT [token]") to accept the connection of websocket. Is possible to add a custom header in header request?

**Comment by gilmaimon** [comment]
Hi, thanks! I'm glad you like the library and find it useful.

It's not possible at the moment, but it won't be very difficult to add. Give me 24 hours (max) and it will be ready!

Best regards,
Gil.

**Comment by mmcArg** [comment]
24hs max!!!!! you are my idol !!!!!! Thanks!!!!!

**Comment by gilmaimon** [comment]
How about 4 hours max 😃 

Thanks for the kind words, Iv'e added an `addHeader` method to `WebsocketsClient`. Just make sure you call it before you call `connect`.

Example:

```
client.addHeader("Authorization", "JWT [token]");
```

Wait for version 0.4.8 (it will be in the IDE soon, you can also get it as [ZIP](https://github.com/gilmaimon/ArduinoWebsockets/releases/tag/0.4.8)).

Thanks again for using the library, give it a star if you liked it so more users can notice it. Let me know that you have used the new version and that everything works fine for you.

Have an awesome weekend,
Gil.

**Comment by mmcArg** [comment]
Hi Gil, thanks for your time. For some reason do not work. I have another example made with another library (Links2004), and works ok, but with your example Y can not obtain the websocket. I will make furter test to find the diference and tell you. Regards!!!!

**Comment by gilmaimon** [comment]
That's odd. Can you show me your code?

**Comment by adelin-mcbsoft** [comment]
Hey Gil, cool new feature, I was also looking for this!
I confirm it works (tested with _v0.4.9_).
(...and man, you are fast! 😄 ).

@mmcArg - make sure you're not behind a proxy server which does not forward the headers; may be the case.

Keep up the good work,
Many thanks Gil,

Best,
A.

**Comment by gilmaimon** [comment]
> Hey Gil (@gilmaimon), cool new feature, I was also looking for this!
> I confirm it works (tested with _v0.4.9_).
> (...and man, you are fast! 😄 ).
> 
> @mmcArg - make sure you're not behind a proxy server which does not forward the headers; may be the case. And also, this must be called **BEFORE** `client.connect()` .
> 
> Keep up the good work,
> Many thanks Gil,
> 
> Best,
> A.

Awesome as always, Thanks Adelin!

Gil.
