### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by DennisChatzim** [gilmaimon/ArduinoWebsockets#27]
Hi.
This library looks like exactly what I need but I cannot compile.
Initially I had a syntax error in "ws_common.hpp" with the "#include <string" I changed it to -> "#include <string.h>" and it was fixed.
But the next one I cannot fix it and it is related to "#include <memory.h>" inside the file "websockets_endpoint.hpp".

COMPILER ERROR ------->
In file included from ...Documents/Arduino/libraries/ArduinoWebsockets-0.4.9/src/tiny_websockets/client.hpp:6:0,
                 from ... Documents/Arduino/libraries/ArduinoWebsockets-0.4.9/src/ArduinoWebsockets.h:5,
                 from ...Documents/Arduino/libraries/ArduinoWebsockets-0.4.9/src/tiny_websockets/internals/websockets_endpoint.hpp:7:10: fatal error: memory.h: No such file or directory
 #include <memory.h>
          ^~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.
<-------END OF COMPILER ERROR

Please help !

**Comment by gilmaimon** [comment]
Hi Dennis!

Looks like you are trying to compile this library with an Arduino mega, but currently the library only supports ESP32 and ESP8266 boards.

Adding support for other boards will take time, and currently is not planned.

Sorry :(

Best regards,
Gil.

**Comment by DennisChatzim** [comment]
Thanks a lot for your super fast response !
I will try to create an iOS app and access this Arduino server using web sockets for fastest performance.
Do you have any suggestions related to this project ? 
I want to Access the Arduino server from external network using a custom iOS app for sending and reading data to and from Arduino using ONLY sockets !

(I just ordered 2 ESP32 boards of them from here: https://www.aliexpress.com/item/33038162831.html?&srcSns=sns_Copy&tid=white_backgroup_101&mb=e1ZJajPEVEMwbOg&tt=sns_Copy&aff_platform=default&cpt=1565328921466&sk=Ye0jDCG&aff_trace_key=1388d154c88a4d158f809fd50c108018-1565328921466-04446-Ye0jDCG&businessType=ProductDetail&platform=AE&terminal_id=9cbd87aad5c2478eac1f46668bc439b3
I will wait for them and try again setting an Arduino server.
)

**Comment by gilmaimon** [comment]
Hi,

Well, if you want to access the Arduino remotely you will need to setup port-forwarding on your local network (via your router settings). But, I must ask why Arduino?
 
I mean, ESP and Arduino boards are very very (very) weak and won't handle demanding computations. They are great when you want to do phisycal tasks, like control devices and sensors. If that's what you want to do with your app, esp32 is perfect! Otherwise, If you just need some computing power for a server I recommend AWS or other VPS service, and definitely not an Arduino.

If you want to have your own local server, and you are just looking for cheap computation power - consider a raspberry pi :)

Maybe I just didn't understand correctly your requirements. If so, please share more about your project 😃 

Gil.

**Comment by DennisChatzim** [comment]
I totally agree with everything you said which means that I am in the right path !
DyDNS and port forwarding are a MUST do in this project, yes.
Yes, I want to use ESP32 because the only thing that I want to do is what Blynk - app does without the need of an expensive machine, or complicated setups etc.
I want to keep the cost as low as possible and build very very useful features which are based only of Switches, leds and sensors !
I don't need complicated tasks, only turning on relays, leds, detects sensors and smart home automation but with very minimal setup.
I want to build a small iOT system based on these really tiny ESP32 with DIY setup and totally custom features.
For the Rasberry PI I don't have knowledge I am not so fun of python :(
The advantage with the setup of ESP32 and iOS app will be that:
1. the cost will be minimum, 
2. the cables and wiring also minimum, 
3. the power also minimum, 
4. the code with your great library minimum
5. The sensors or other modules whichh can be used with Arduino will be very cheap 
6. and the iOS app can have very fast response because it will be based on sockets
7. and nice custom native iOS UI based on the needs. I have seen Arduino-webServer-http solutions but I really hate these webViews and the speed/performance will be awful.  
Also I can have 3-4 different ESP32s in the same network communicating each other, right ?
All of them can be in sync and gather data of all the rest boards in the same network
I can have only one of them act as the server and the iOS app will communicate only with that server-board.
Then the server-board can request values and sensor data from all the rest boards around the house.
Using your great library I can send and receive data from multiple ESP32s in the same network very easily, am I right ?
As soon as I have something useful I will try to post an article or an intractable of what I did !
I was also wondering: All these nice code and library that you have done is just for free right ? You don't make money of all this kind of work ? Can I make money if I build a great iOT service like the one that I just described ?
Thanks a lot for everything !

**Comment by gilmaimon** [comment]
Ok, sounds like a very cool project!

> Also I can have 3-4 different ESP32s in the same network communicating each other, right ?

Sure, but it depends on how you set them up. I mean in order for them to know the ip's of one another you will either need to make some kind of dynamic-configuration mechanism. Or make them all get their configuration from a central server. Think about it.

> Using your great library I can send and receive data from multiple ESP32s in the same network very easily, am I right ?

Yes, but to me it looks like you need the opposite, meaning you need one esp32 to handle multiple IOS devices, right?

> Can I make money if I build a great iOT service like the one that I just described ?

Let me know, I'm more into free OS software 😃 


I've read your post, I think you should sort out the exact details and design for your system. How components know of each other, how exactly they will communicate. Also, in your case I think a solution with MQTT is much better. It will save you a lot of code, and will help you with stuff like devices discoverability and management. MQTT is pretty much tailored to your needs, and there are plenty of tutorials about it with combination of ESP32.

Good luck!

**Comment by DennisChatzim** [comment]
OMG !
After finding this tutorial:
http://www.iotsharing.com/2017/05/how-to-use-mqtt-to-build-smart-home-arduino-esp32.html
this service: https://www.cloudmqtt.com/
and this iOS app:
https://apps.apple.com/us/app/mqtt-buddy/id1252991874

I realised that I can do the above project using existing iOS apps and services without the need to build something from scratch !
So the question now is:
Why would I need this library if all the logic can be ready made from the above stuff/services ?
Why would I need to use sockets with Arduino and not the ready made service MQTT ?
Thanks a lot again for your super useful info that you are providing me !

**Comment by gilmaimon** [comment]
Hi, I'm always glad to help!

Actually if you use MQTT you don't need this library :) Any Arduino MQTT library will be all you need.

I am not familiar with cayene-myDevices, so I can't say.

Again I'm glad I could help, I wish you best of luck with your project and a great weekend!

**Comment by DennisChatzim** [comment]
I will try playing with Cayene and I will also try to use your library as a test.
then I will compare the performance and the speed while sending/receiving data to see if I notice important differences.
Maybe it is convenient to use both libraries. I could use this library for the local data exchange between the ESP32s in the same local network and then use only one of them to connect to MQTT service, I will decide after my initial tests-learning.
Thanks a  lot for your guidance man, I am really glad for this conversation, have a great weekend too !

**Comment by gilmaimon** [comment]
😃
