### ISSUE TITLE
ESP8266/ESP32 error in internal receive

### ISSUE THREAD

**Issue by gilmaimon** [gilmaimon/ArduinoWebsockets#3]
First described in this issue #2.

When continusly sending and receiving messages (with no/very-short delays) on esp8266 a message with bad values is read (opcode and fin makes no sense).

Does the issue occurs on ESP32?

**Comment by gilmaimon** [comment]
ESP8266 networking was fixed in this release b7c00e38cc996033cf107903f0a07dd0acc3aefd
Now communication is sync. ESP32's networking is still problematic when sending many messages without any (or very little) delay.

This issue might help: https://github.com/espressif/arduino-esp32/issues/2576

**Comment by gilmaimon** [comment]
Both platforms (Esp8266 and 32) adressed in release b1164a6da63131355e70fc0ddfeb030bfc80f007
Current solution is the usage of `setNoDelay(true)`

**Comment by ramdor** [comment]
Seems to be a good compromise Gil. There is still the rare possibility of corruption and a disconnection, which is now handled fine anyway.  I feel with the flush/nosync the communications became far too slow. The noDelay which also stops the nagle algorithm is ok 👍 Cheers.

**Comment by gilmaimon** [comment]
@ramdor Have you experianced any disconnection with non-intensive usage?

**Comment by ramdor** [comment]
@gilmaimon no, I have left my project run for hours and hours, no disconnects. It is sending and receiving a 20char message about 5 per second when 'idle'. I will add some debug code tomorrow to count up any reconnects, and keep a message count,, and display on the oled1306 👍

**Comment by ramdor** [comment]
some initial results of just over 1 hour run time

sent message string from esp8266 :  `rx_smeter:0,0;`
received message string into esp8266 :  `rx_smeter:0,0,-123;`

connection attempts : 1
successful connections : 1
send message count : 82453
received message count : 82453

which works out to be around 23 out bound messages per second, 23 inbound/s

I would say it is working fine !!! 👍  x  💯

**Comment by ramdor** [comment]
ok, 12hrs...
connection attempts : 1
successful connections : 1
send message count : 907613
received message count : 907613

averaged about 21 msgs per second 🥇

**Comment by gilmaimon** [comment]
@ramdor Awesome. Thank You!

I'm keeping the issue open for few more days just in case there will be any additional input :)

**Comment by gilmaimon** [comment]
Thank You @ramdor for the help. I am closing this issue until further re-productions.
