### ISSUE TITLE
How To Make Server Stay Connected to Client, Send INT Value?

### ISSUE THREAD

**Issue by TSJim** [gilmaimon/ArduinoWebsockets#30]
Hi Gil...

This library is GREAT!!! Much needed.  All the previous ones seemed very complex, especially for noobs like me.  ;)

How would I use your library to create a server that just sends out the contents of an INT variable to connected clients every second, and doesn't disconnect the client?

Thanks!

--
Jim

**Comment by gilmaimon** [comment]
Hi Jim!

I agree! Other libraries seemed complex to me as well. And complexity is always a bad thing, not only for noobs :)

You need to think of a way to manage multiple clients. You can have a vector or list of connected clients. 

For each loop, or on some fixed interval you can remove from the list clients that were disconnected (use `client.available()` to see if the client is still connected).

You can also ping the clients on fixed intervals in order to make sure they are still alive and that the TCP connection is really ok.

Then, in order to send an int to the client you can go the easy way, which is to convert it to a string. You can also convert an int pointer to byte array and send it using `sendBinary`. I'm currently on mobile, but let me know if want some code samples.

Gil.

**Comment by TSJim** [comment]
Hi Gil...

I really appreciate your fast reply!

Here is my code that I modified from your "Esp32-Server" example sketch.

All I'm doing is setting my variable "print_type_int" to either "2" or "3"
with random for now, then copying it to a String "print_type_string".  Then
in the loop(), I'm sending the "print_type_string" value directly to the
client with the line "client.send(print_type_string);".

When the client connects, the server immediately sends the value of
"print_type_string" just fine.  Yay!

The problem is that the server disconnects the client as soon as the
message is sent to the client.  What I want is for the value just to be
sent to the client every second continuously, and the client should stay
connected to the server.

Can you please give me an example of how I can tell the server to not
disconnect the client?

Thanks!

Here's my modified code that works and sends the "2" or "3" to the client
every time the client connects.  If you are using an email reader that
preserves formatting, the yellow text is stuff I added or modified, and the red
text is your code that I commented out:

*/**
*  Minimal Esp32 Websockets Server*

*  This sketch:*
*        1. Connects to a WiFi network*
*        2. Starts a websocket server on port 80*
*        3. Waits for connections*
*        4. Once a client connects, it wait for a message from the client*
*        5. Sends an "echo" message to the client*
*        6. closes the connection and goes back to step 3*

*  Hardware:*
*        For this sketch you only need an ESP32 board.*

*  Created 15/02/2019*
*  By Gil Maimon*
*  https://github.com/gilmaimon/ArduinoWebsockets
<https://github.com/gilmaimon/ArduinoWebsockets>*
**/*

*#include <ArduinoWebsockets.h>*
*#include <WiFi.h>*

*const char* ssid = "GEE"; //Enter SSID*
*const char* password = "catface1!"; //Enter Password*

*int print_type_int = 0;*
*String print_type_string = "";*

*using namespace websockets;*

*WebsocketsServer server;*
*void setup() {*
*  Serial.begin(115200);*
*  // Connect to wifi*
*  WiFi.begin(ssid, password);*

*  // Wait some time to connect to wifi*
*  for(int i = 0; i < 15 && WiFi.status() != WL_CONNECTED; i++) {*
*      Serial.print(".");*
*      delay(1000);*
*  }*

*  Serial.println("");*
*  Serial.println("WiFi connected");*
*  Serial.println("IP address: ");*
*  Serial.println(WiFi.localIP());   //You can get IP address assigned to
ESP*

*  server.listen(80);*
*  Serial.print("Is server live? ");*
*  Serial.println(server.available());*
*}*

*void loop() {*

*  WebsocketsClient client = server.accept();*

*  client.send(print_type_string);*

*  //if(client.available()) {*
*    //WebsocketsMessage msg = client.readBlocking();*

*    // log*
*    //Serial.print("Got Message: ");*
*    //Serial.println(msg.data());*

*    // return echo*
*    //client.send("Echo: " + msg.data());*

*    // Read new value for int "print_type:*
*    print_type_int = random(2,4);  // Will return either "2" or "3"*
*    Serial.print("print_type_int: "); Serial.println(print_type_int);*

*    // Convert print_type_int to a String:*
*    print_type_string = print_type_int;*
*    Serial.print("print_type_string: ");
Serial.println(print_type_string);*

*    client.send(print_type_string);*

*    // close the connection*
*    //client.close();*
*  // }*

*  Serial.print("client.available(): ");
Serial.println(client.available());*

*  delay(1000);*

*}*


Thank you again!  Can I buy you some beer or coffee somehow for your help?

--
Jim Newton
jimn9970@gmail.com
1 (650) 521-2840

**Comment by gilmaimon** [comment]
I'm glad to help Jim :)

What happens here is that `WebsocketsClient` will call close when it goes out of scope. Meaning once you lost the variable (when `loop` ends) you loose the "handle" to that object, and because I don't want the connection to get lost and the resources to stay open, the connection will be closed even if you don't call `close` explicitly.

To solve this, you need to use some sort of collection to store all your ongoing connections. In the code below I used a vector.

This code will work fine for you:
```cpp
/*
  Minimal Esp32 Websockets Server

  This sketch:
        1. Connects to a WiFi network
        2. Starts a websocket server on port 80
        3. Waits for connections
        4. Once a client connects, it wait for a message from the client
        5. Sends an "echo" message to the client
        6. closes the connection and goes back to step 3

  Hardware:
        For this sketch you only need an ESP32 board.

  Created 15/02/2019
  By Gil Maimon
  https://github.com/gilmaimon/ArduinoWebsockets
*/

#include <ArduinoWebsockets.h>
#include <WiFi.h>

const char* ssid = "GEE"; //Enter SSID
const char* password = "catface1!"; //Enter Password

int print_type_int = 0;
String print_type_string = "";

using namespace websockets;

WebsocketsServer server;

std::vector<WebsocketsClient> connectedClients;

void setup() {
  Serial.begin(115200);
  // Connect to wifi
  WiFi.begin(ssid, password);

  // Wait some time to connect to wifi
  for(int i = 0; i < 15 && WiFi.status() != WL_CONNECTED; i++) {
      Serial.print(".");
      delay(1000);
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());   //You can get IP address assigned to ESP

  server.listen(80);
  Serial.print("Is server live? ");
  Serial.println(server.available());
}

void loop() {
    // First, lets see if there are clients which wants to connect to our server
    while (server.poll()) {
        // If we are here, there is another client willing to connect!
        // Lets accept the connection, and add it to the list of clients
        WebsocketsClient client = server.accept();

        // Lets keep a refernce to the client in our collection, so We won't loose it and close the connection early
        connectedClients.push_back(client);
    }


    // Now, lets make sure that all the clients that are in our vector are actually still connected
    std::vector<WebsocketsClient> actuallyConnectedClients;
    // For every client in connectedClients:
    for(const WebsocketsClient& client : connectedClients) {
        // If the client is still connected, add it to the new list
        if (client.available()) {
            actuallyConnectedClients.push_back(client);
        }
    }
    // Now we are pretty sure that everyone in connectedClients are actually connected
    connectedClients = actuallyConnectedClients;

    // Lets update the int value, Read new value for int "print_type:
    print_type_int = random(2,4);  // Will return either "2" or "3"
    Serial.print("print_type_int: "); Serial.println(print_type_int);
    // Convert print_type_int to a String:
    print_type_string = print_type_int;
    Serial.print("print_type_string: "); Serial.println(print_type_string);


    // Last, we send the new value to all the connected clients
    for(const WebsocketsClient& client : connectedClients) {
        // If the client is still connected, add it to the new list
        client.send(print_type_string);
    } 

    // Sleep until next iteration
    Serial.print("Num of connected clients: "); Serial.println(connectedClients.size());
    delay(1000);
}
```

What I do here:
- First I accept anyone willing to connect (if there are any) and add them to the list of clients
- I make sure everyone in the list of clients that are still connected, and I keep only the ones connected
- I use your code to calculate the new random value
- I send it to all the clients
- Sleep, and repeat ♻️ 

I've added detailed comments, make sure you read them and understand what's happening. I made them very detailed because I don't know exactly what your level is, and I want this to be useful to anyone in the future. I'll be glad to further explain anything you wish.

I already drink way too much coffee 😄 The best way to contribute is to use the library and have fun with it!

Gil.

**Comment by TSJim** [comment]
Hi Gil...

Your code on line 92 of the new sketch which is:

`client.send(print_type_string);`

Gives the following error on compiling:

`passing 'const websockets::WebsocketsClient' as 'this' argument discards qualifiers [-fpermissive]`

I tried to research this error to see if I could fix it, but it looks like I would have to change something about the const usage in the "Arduino/libraries/ArduinoWebsockets/src/tiny_websockets/internals/websockets_endpoint.hpp " file, which is way beyond my knowledge yet.

I also tried making the "print_type_string" a const and passing that to the `client.send(print_type_string);` function in the sketch, but that didn't change anything.

Can you understand why this error is happening?

Thank you so much!!!

--
Jim

**Comment by gilmaimon** [comment]
> Hi Gil...
> 
> Your code on line 92 of the new sketch which is:
> 
> `client.send(print_type_string);`
> 
> Gives the following error on compiling:
> 
> `passing 'const websockets::WebsocketsClient' as 'this' argument discards qualifiers [-fpermissive]`
> 
> I tried to research this error to see if I could fix it, but it looks like I would have to change something about the const usage in the "Arduino/libraries/ArduinoWebsockets/src/tiny_websockets/internals/websockets_endpoint.hpp " file, which is way beyond my knowledge yet.
> 
> I also tried making the "print_type_string" a const and passing that to the `client.send(print_type_string);` function in the sketch, but that didn't change anything.
> 
> Can you understand why this error is happening?
> 
> Thank you so much!!!
> 
> --
> Jim

Sorry mate! I uploaded an older version of the code. 
This should work:
```cpp
#include <ArduinoWebsockets.h>
#include <WiFi.h>

const char* ssid = "GEE"; //Enter SSID
const char* password = "catface1!"; //Enter Password

int print_type_int = 0;
String print_type_string = "";

using namespace websockets;

WebsocketsServer server;

std::vector<WebsocketsClient> connectedClients;

void setup() {
  Serial.begin(115200);
  // Connect to wifi
  WiFi.begin(ssid, password);

  // Wait some time to connect to wifi
  for(int i = 0; i < 15 && WiFi.status() != WL_CONNECTED; i++) {
      Serial.print(".");
      delay(1000);
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());   //You can get IP address assigned to ESP

  server.listen(80);
  Serial.print("Is server live? ");
  Serial.println(server.available());
}

void loop() {
    // First, lets see if there are clients which wants to connect to our server
    while (server.poll()) {
        // If we are here, there is another client willing to connect!
        // Lets accept the connection, and add it to the list of clients
        WebsocketsClient client = server.accept();

        // Lets keep a refernce to the client in our collection, so We won't loose it and close the connection early
        connectedClients.push_back(client);
    }


    // Now, lets make sure that all the clients that are in our vector are actually still connected
    std::vector<WebsocketsClient> actuallyConnectedClients;
    // For every client in connectedClients:
    for(WebsocketsClient& client : connectedClients) {
        // If the client is still connected, add it to the new list
        if (client.available()) {
            actuallyConnectedClients.push_back(client);
        }
    }


    // Now we are pretty sure that everyone in connectedClients are actually connected
    connectedClients = actuallyConnectedClients;

    // Lets update the int value, Read new value for int "print_type:
    print_type_int = random(2,4);  // Will return either "2" or "3"
    Serial.print("print_type_int: "); Serial.println(print_type_int);
    // Convert print_type_int to a String:
    print_type_string = print_type_int;
    Serial.print("print_type_string: "); Serial.println(print_type_string);


    // Last, we send the new value to all the connected clients
    for(WebsocketsClient& client : connectedClients) {
        // If the client is still connected, add it to the new list
        client.send(print_type_string);
    } 

    // Sleep until next iteration
    Serial.print("Num of connected clients: "); Serial.println(connectedClients.size());
    delay(1000);
}
```


Gil 😄

**Comment by TSJim** [comment]
Hi Gil...

YAY!!! It works great!  Thank you SOOO much!

--
Jim

**Comment by gilmaimon** [comment]
😄
