### ISSUE TITLE
Support Arduino UNO wifi rev 2

### ISSUE THREAD

**Issue by webberig** [gilmaimon/ArduinoWebsockets#31]
I'm trying to setup a websocket server on my Arduino UNO wifi rev 2, but as soon as I include ArduinoWebsockets to my script, I get a compilation error:
```
In file included from /.../Arduino/libraries/ArduinoWebsockets/src/tiny_websockets/message.hpp:3:0,
                 from /.../Arduino/libraries/ArduinoWebsockets/src/ArduinoWebsockets.h:4,
                 from /.../Arduino/distancemeterWifi/distancemeterWifi.ino:3:
/.../Arduino/libraries/ArduinoWebsockets/src/tiny_websockets/internals/ws_common.hpp:4:10: fatal error: string: No such file or directory
 #include <string>
          ^~~~~~~~
compilation terminated.
exit status 1
```

I'm fairly new to the programming language, so I have no clue what is causing this... Why is this importing "string" ?

**Comment by gilmaimon** [comment]
Hi,

This library currently only supports ESP32 and ESP8266 which is why you are getting compilation errors..

There is no plan currently to support other boards, I'll consider grabbing an Uno WiFi rev 2 and supporting it.

Gil

**Comment by gilmaimon** [comment]
Not going to develop this myself. Contributions for further support are welcomed and I describe briefly how to do so [here](https://github.com/gilmaimon/ArduinoWebsockets/issues/52#issuecomment-558805092).
