### ISSUE TITLE
Error compiling esp8266 client example

### ISSUE THREAD

**Issue by denden4444** [gilmaimon/ArduinoWebsockets#36]
Hi Gil 

I am experiencing a compile error .. 
`
In file included from C:\Users\den\Documents\Arduino\libraries\arduino_290866\src/tiny_websockets/internals/ws_common.hpp:47:0,

                 from C:\Users\den\Documents\Arduino\libraries\arduino_290866\src/tiny_websockets/message.hpp:3,

                 from C:\Users\den\Documents\Arduino\libraries\arduino_290866\src/ArduinoWebsockets.h:4,

                 from C:\Users\den\Documents\Arduino\libraries\arduino_290866\examples\Esp8266-Client\Esp8266-Client.ino:19:

C:\Users\den\Documents\Arduino\libraries\arduino_290866\src/tiny_websockets/network/esp8266/esp8266_tcp.hpp: In member function 'void websockets::network::SecuredEsp8266TcpClient::setInsecure()':

C:\Users\den\Documents\Arduino\libraries\arduino_290866\src/tiny_websockets/network/esp8266/esp8266_tcp.hpp:18:20: error: 'class WiFiClientSecure' has no member named 'setInsecure'

       this->client.setInsecure();

                    ^

C:\Users\den\Documents\Arduino\libraries\arduino_290866\src/tiny_websockets/network/esp8266/esp8266_tcp.hpp: In member function 'void websockets::network::SecuredEsp8266TcpClient::setFingerprint(const char*)':

C:\Users\den\Documents\Arduino\libraries\arduino_290866\src/tiny_websockets/network/esp8266/esp8266_tcp.hpp:22:20: error: 'class WiFiClientSecure' has no member named 'setFingerprint'

       this->client.setFingerprint(fingerprint);

                    ^

exit status 1
Error compiling for board Generic ESP8266 Module.
`

Could you please shed some light ?

Kind regards

Den

**Comment by gilmaimon** [comment]
Hi, lets handle both issues here (https://github.com/gilmaimon/ArduinoWebsockets/issues/37)

**Comment by gilmaimon** [comment]
Can you write here what version of esp8266 Arduino libraries you are using?

**Comment by denden4444** [comment]
Hi Gil 

Not sure what you are asking specifically ?
Is it your websocket library info you need or those for esp8266 ?

**Comment by gilmaimon** [comment]
Hi,

I mean the libraries that are installed when you add esp8266 in the board manager.

Go to `tools`-> `boards` -> `Boards Manager` and search for `esp8266`. The version should be written on the top of the search result. For example I have 2.5.2 which works well. Try installing the latest version and see if the issue persists

**Comment by denden4444** [comment]
Hi Gil 

Yay thank you for the reply.
Problem solved :-) !
You can close this issue.
Also for people experiencing an issue with updating boards versions here's a great reference : 
[https://arduino-esp8266.readthedocs.io/en/latest/faq/a04-board-generic-is-unknown.html](url)
I hope it helps someone.

Den

**Comment by gilmaimon** [comment]
Awesome! I'm sure this issue will be useful for someone in the future.

Also, feel free to ask anything! I'm also available on email (and Discord) if you have any small usage questions that shouldn't be in a separate issue.

Good luck and have fun!
Gil.
