### ISSUE TITLE
Error compiling ESP8266 server example 

### ISSUE THREAD

**Issue by denden4444** [gilmaimon/ArduinoWebsockets#37]
Hi Gil 

ESP8266 server example won't compile .. (similar issues to my previous post about the client example not compiling.
`
In file included from C:\Users\den\Documents\Arduino\libraries\arduino_290866\src/tiny_websockets/internals/ws_common.hpp:47:0,

                 from C:\Users\den\Documents\Arduino\libraries\arduino_290866\src/tiny_websockets/message.hpp:3,

                 from C:\Users\den\Documents\Arduino\libraries\arduino_290866\src/ArduinoWebsockets.h:4,

                 from C:\Users\den\AppData\Local\Temp\arduino_modified_sketch_512897\Esp8266-Server.ino:20:

C:\Users\den\Documents\Arduino\libraries\arduino_290866\src/tiny_websockets/network/esp8266/esp8266_tcp.hpp: In member function 'void websockets::network::SecuredEsp8266TcpClient::setInsecure()':

C:\Users\den\Documents\Arduino\libraries\arduino_290866\src/tiny_websockets/network/esp8266/esp8266_tcp.hpp:18:20: error: 'class WiFiClientSecure' has no member named 'setInsecure'

       this->client.setInsecure();

                    ^

C:\Users\den\Documents\Arduino\libraries\arduino_290866\src/tiny_websockets/network/esp8266/esp8266_tcp.hpp: In member function 'void websockets::network::SecuredEsp8266TcpClient::setFingerprint(const char*)':

C:\Users\den\Documents\Arduino\libraries\arduino_290866\src/tiny_websockets/network/esp8266/esp8266_tcp.hpp:22:20: error: 'class WiFiClientSecure' has no member named 'setFingerprint'

       this->client.setFingerprint(fingerprint);

                    ^

exit status 1
Error compiling for board Generic ESP8266 Module.

Hope you can help 

Kind regards

Den
`

**Comment by gilmaimon** [comment]
Already conversed here https://github.com/gilmaimon/ArduinoWebsockets/issues/36
