### ISSUE TITLE
How to use the payload (message.data())

### ISSUE THREAD

**Issue by denden4444** [gilmaimon/ArduinoWebsockets#38]
Hi Gil

Both server and client are working great so far.
I would like to replace the existing websockets library I have been using with your one.

For this I need to know how to use message.data() and what it is .. array struct etc and what format the data is in ?

In the previous library I was working with a payload array and am doing comparisons like :
`if (payload[0] == '#') {  `

If you would be so kind as to expand on this a little it would save me oodles of time in switching my code over to start using and and use your awesome library.

I love the way it has very granular control. 

I'm about to start on creating a client and server in one sketch for testing.Will update you on progress too.

I look forward to your reply.

Den

**Comment by gilmaimon** [comment]
Hi Den,
I'm glad to hear it's going well.

The returned object is an Arduino `String`. You should be able to access it just like a char array. You can also call `.c_str()` on the string and it will return you the underlying buffer.

Good luck and best regards,
Gil.

**Comment by denden4444** [comment]
Hi Gil 
Thanks for the well wishes ;-) 
Do you possibly have an example ? 
Instead of String is there an existing char array that can be accessed ? This would save having to use more memory space to create extra variables for character field tests etc.

My incoming message looks like this : 
`# 100 test test 1234567890 1234567890 Normal 1234 12 1 1`

I hope you can help 
PS.
Not quite sure what you mean by this : 
` You can also call .c_str() on the string and it will return you the underlying buffer.`

Kind regards 
Den

**Comment by gilmaimon** [comment]
I mean you could do:
```c++
const char* message_raw_data = message.data().c_str();
```

And then use the `char*` as you did before. 

Returning a char* might sound like a better idea but it has so many issues with memory management and ownership problems. I think it worth spending some efficiency in order to protect the user.

You could do:
```c++
auto data = message.data();

if (data[0] == '#') {
  // Do something
}
```

**Comment by denden4444** [comment]
Hi Gill

Thank you kindly for the advice and code bits .. experimenting as we speak :-)

Kind regards
Den

**Comment by gilmaimon** [comment]
:)
