### ISSUE TITLE
How to handle multiple clients from server side ?

### ISSUE THREAD

**Issue by denden4444** [gilmaimon/ArduinoWebsockets#39]
Hi Gil 

Part of migrating my existing code to use your code involves handling multiple clients from the server side.

Is this possible and how do you handle this ?
Specifically :
How do you handle multiple clients and replies to each individual client ?
How do you identify each in turn and their specific data back and forth ?

Kind regards
Den

**Comment by gilmaimon** [comment]
Hi Den,

As Iv'e commented in another issue: it is possible and there is an example in the wiki:
https://github.com/gilmaimon/TinyWebsockets/wiki/Server#advanced-echo-server-can-handle-multiple-clients-at-the-same-time

Lets keep all the usage-questions in this thread: https://github.com/gilmaimon/ArduinoWebsockets/issues/35
