### ISSUE TITLE
Why my webSocket Server Only once after that Connection Close on WebsocketServer 

### ISSUE THREAD

**Issue by hananloser** [gilmaimon/ArduinoWebsockets#40]
223index.html:39 WebSocket is already in CLOSING or CLOSED state.
(anonymous) @ index.html:39
setInterval (async)
ws.onopen @ index.html:38

**Comment by gilmaimon** [comment]
Hi,

You must provide more information for me to solve anything here... 
Please write:
- The code you are using
- The version of the library
- Any other components you have running (a browser client?)
- What you expect to happen
- What happens

Gil.

**Comment by gilmaimon** [comment]
This issue will be close due to inactivity soon.
