### ISSUE TITLE
How to set server to non-blocking while in main loop ?

### ISSUE THREAD

**Issue by denden4444** [gilmaimon/ArduinoWebsockets#41]
Hi Gil 

How do you set the server to be non-blocking in the main loop , in other words to allow other code/functions to run ?
For example I have the following :
```
void loop() {

  server.handleClient();                      // run the web server
  //websockets server
  WebsocketsClient client = wsserver.accept();
  if (client.available()) {
    WebsocketsMessage msg = client.readBlocking();

    // log
    Serial.print("Got Message: ");
    Serial.println(msg.data());
  }

  // return echo
  client.send("Echo: " + msg.data());

  // close the connection
  client.close();
}//endof if client.available


//end of webSocket Server

SOME_OTHER_FUNCTION();
SOME_OTHER_FUNCTION_TWO();
//etc
//start from beginning of loop again
}
```

Look forward to your reply as always :-)

Den

**Comment by gilmaimon** [comment]
Hi Den...
1. Please read my comment here https://github.com/gilmaimon/ArduinoWebsockets/issues/35#issuecomment-539246189
2. It's in the docs ([Wiki](https://github.com/gilmaimon/TinyWebsockets/wiki/Server#checking-availablity))

Lets keep all of your question in a single thread or in some other medium.
