### ISSUE TITLE
Basic connection question 

### ISSUE THREAD

**Issue by elC0mpa** [gilmaimon/ArduinoWebsockets#45]
Hello, I would like to use this library to develop a websocketclient wich will communicate with a php laravel websocketserver. 
This websocket server is currently running and comunicating with other websocket clients written in javascript. 
new WebSocket(ws://192.168.1.12:6001); 
Above is shown the way in wich javascript objects are being created (these objects can comunicate with the websocket server).
This is my question, when i call the connect method, I would like to pass the host, the port and the path independiently as shown below, in this case its pretty easy to identify the host and the port, but i have some doubts about which will be the correct path. 
#define IP_ADDRESS "192.168.1.12" 
#define PORT 6001
#define PATH "/" 
websocket.connect(IP_ADDRESS, PORT, PATH);  
I know this looks like a basic question, but i would like to know which is the correct answer. 
Thanks in advance

**Comment by gilmaimon** [comment]
Hi @elC0mpa ,

The path is the default path (`"/"`)
You call also call `client.connect("ws://192.168.1.12:6001");` and it will work fine, the library will know how to parse the string and connect you accordingly 😃 

Gil.

**Comment by elC0mpa** [comment]
Thanks @gilmaimon, I already knew that i could use the other definition of connect method, but i just wanted to know which would be the correct path. Thanks for your answer

**Comment by gilmaimon** [comment]
Glad I could help 😄 

Good luck!
Gil.
