### ISSUE TITLE
Library example is not compiling

### ISSUE THREAD

**Issue by maubaum** [gilmaimon/ArduinoWebsockets#48]
**Describe the bug**
I have just downloaded the latest version of the library on Arduino IDE.

I am trying to complile the example "Minimal Esp8266 Websockets Client" sketch in a NodeMCU board and I am receiving "Error compiling for board NodeMCU 1.0 (ESP-12E Module)." 

Is the library compatible with NodeMCU 1.0 board?

**Comment by maubaum** [comment]
I found the solution in closed issues.

**Comment by gilmaimon** [comment]
:)
