### ISSUE TITLE
connect() timeout

### ISSUE THREAD

**Issue by RainGrid** [gilmaimon/ArduinoWebsockets#55]
**Describe the bug**
Infinite connection process if wifi is not connected

**To Reproduce**
- latest library
- ESP32

The connection process is not timed out if wifi lost the connection or wifi was not connected.
Usually wifi gets DISCONNECTED status after Websocket loses the connection, so the connection process stacks ESP

**Comment by adelin-mcbsoft** [comment]
Hi @RainGrid ,

Take a look at [this topic (issue no. #14)](https://github.com/gilmaimon/ArduinoWebsockets/issues/14).
It might be related to it and it may shed some light.

Thanks,
Best,
A.

**Comment by gilmaimon** [comment]
Hi, that's odd...
I'm running this sketch:
```c++
#include <ArduinoWebsockets.h>
#include <WiFi.h>

const char* ssid = "ssid"; //Enter SSID
const char* password = "password"; //Enter Password

using namespace websockets;

WebsocketsClient client;
void setup() {
    Serial.begin(115200);
    // Connect to wifi
    WiFi.begin(ssid, password);

    // Wait some time to connect to wifi
    for(int i = 0; i < 10 && WiFi.status() != WL_CONNECTED; i++) {
        Serial.print(".");
        delay(1000);
    }

    // Check if connected to wifi
    if(WiFi.status() != WL_CONNECTED) {
        Serial.println("No Wifi!, But lest keep going");
    }

    Serial.println("Connected to Wifi, Connecting to server.");
    // try to connect to Websockets server
    bool connected = client.connect("ws://1.2.3.4:8080");
    if(connected) {
        Serial.println("Connecetd!");
        client.send("Hello Server");
    } else {
        Serial.println("Not Connected!");
    }
    
    // run callback when messages are received
    client.onMessage([&](WebsocketsMessage message){
        Serial.print("Got Message: ");
        Serial.println(message.data());
    });
}

void loop() {
    // let the websockets client check for incoming messages
    if(client.available()) {
        client.poll();
    }
    delay(500);
}
```
 
And the program runs just fine, and prints "Not Connected!".
Please make sure you really do have the latest library version (write here what you have), and make sure you have the latest esp32 libs (1.0.4 is the latest stable, which I have).
If all that does not help, turn on debugging logs and lets see what's up :)

Thanks for opening the issue,
Gil.

**Comment by RainGrid** [comment]
@gilmaimon hi, you are right, the problem was in the Esp lib (v 1.0.2). Works well with v 1.0.4. Thanks for the help.

**Comment by gilmaimon** [comment]
Awesome! I'm glad I could help and thanks for taking the time to open the issue.  

Gil.
