### ISSUE TITLE
How to transfer Sec-WebSocket-Protocol when connecting to a WebSocket server?

### ISSUE THREAD

**Issue by DeltaVetal26** [gilmaimon/ArduinoWebsockets#56]
Hi,

How can I implement Sec-WebSocket-Protocol transfer when connecting to a server?
How would I do it through JS:

`let socket = new WebSocket("ws://xxx.xxx.xxx.x:8080/WebSocket/001", ["protocol1", "protocol2"]);`

**Comment by gilmaimon** [comment]
Hi,

The library currently does not support such sub protocols, so there is no way to do it. Consider trying another library.

Gil.

**Comment by DeltaVetal26** [comment]
@gilmaimon 

Thank you for the answer!
