### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by GreenMine** [gilmaimon/ArduinoWebsockets#60]
`In file included from C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/ESP8266WiFi.h:34:0,

                 from C:\Program Files (x86)\Arduino\libraries\ArduinoWebsockets-master\src/tiny_websockets/network/esp8266/esp8266_tcp.hpp:10,

                 from C:\Program Files (x86)\Arduino\libraries\ArduinoWebsockets-master\src/tiny_websockets/internals/ws_common.hpp:47,

                 from C:\Program Files (x86)\Arduino\libraries\ArduinoWebsockets-master\src/tiny_websockets/message.hpp:3,

                 from C:\Program Files (x86)\Arduino\libraries\ArduinoWebsockets-master\src/ArduinoWebsockets.h:4,

                 from C:\Program Files (x86)\Arduino\libraries\ArduinoWebsockets-master\examples\Minimal-Esp8266-Client\Minimal-Esp8266-Client.ino:25:

C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/ESP8266WiFiSTA.h:41:74: error: 'emptyString' was not declared in this scope

         wl_status_t begin(const String& ssid, const String& passphrase = emptyString, int32_t channel = 0, const uint8_t* bssid = NULL, bool connect = true);

                                                                          ^

In file included from C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/ESP8266WiFi.h:35:0,

                 from C:\Program Files (x86)\Arduino\libraries\ArduinoWebsockets-master\src/tiny_websockets/network/esp8266/esp8266_tcp.hpp:10,

                 from C:\Program Files (x86)\Arduino\libraries\ArduinoWebsockets-master\src/tiny_websockets/internals/ws_common.hpp:47,

                 from C:\Program Files (x86)\Arduino\libraries\ArduinoWebsockets-master\src/tiny_websockets/message.hpp:3,

                 from C:\Program Files (x86)\Arduino\libraries\ArduinoWebsockets-master\src/ArduinoWebsockets.h:4,

                 from C:\Program Files (x86)\Arduino\libraries\ArduinoWebsockets-master\examples\Minimal-Esp8266-Client\Minimal-Esp8266-Client.ino:25:

C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/ESP8266WiFiAP.h:40:67: error: 'emptyString' was not declared in this scope

         bool softAP(const String& ssid,const String& passphrase = emptyString,int channel = 1,int ssid_hidden = 0,int max_connection = 4);

                                                                   ^

In file included from C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:29:0,

                 from C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/WiFiClientSecure.h:41,

                 from C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/WiFiServerSecure.h:20,

                 from C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/ESP8266WiFi.h:41,

                 from C:\Program Files (x86)\Arduino\libraries\ArduinoWebsockets-master\src/tiny_websockets/network/esp8266/esp8266_tcp.hpp:10,

                 from C:\Program Files (x86)\Arduino\libraries\ArduinoWebsockets-master\src/tiny_websockets/internals/ws_common.hpp:47,

                 from C:\Program Files (x86)\Arduino\libraries\ArduinoWebsockets-master\src/tiny_websockets/message.hpp:3,

                 from C:\Program Files (x86)\Arduino\libraries\ArduinoWebsockets-master\src/ArduinoWebsockets.h:4,

                 from C:\Program Files (x86)\Arduino\libraries\ArduinoWebsockets-master\examples\Minimal-Esp8266-Client\Minimal-Esp8266-Client.ino:25:

C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/BearSSLHelpers.h:141:44: error: expected class-name before '{' token

 class HashSHA256 : public UpdaterHashClass {

                                            ^

C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/BearSSLHelpers.h:143:18: error: 'virtual void BearSSL::HashSHA256::begin()' marked override, but does not override

     virtual void begin() override;

                  ^

C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/BearSSLHelpers.h:144:18: error: 'virtual void BearSSL::HashSHA256::add(const void*, uint32_t)' marked override, but does not override

     virtual void add(const void *data, uint32_t len) override;

                  ^

C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/BearSSLHelpers.h:145:18: error: 'virtual void BearSSL::HashSHA256::end()' marked override, but does not override

     virtual void end() override;

                  ^

C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/BearSSLHelpers.h:146:17: error: 'virtual int BearSSL::HashSHA256::len()' marked override, but does not override

     virtual int len() override;

                 ^

C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/BearSSLHelpers.h:147:25: error: 'virtual const void* BearSSL::HashSHA256::hash()' marked override, but does not override

     virtual const void *hash() override;

                         ^

C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/BearSSLHelpers.h:148:34: error: 'virtual const unsigned char* BearSSL::HashSHA256::oid()' marked override, but does not override

     virtual const unsigned char *oid() override;

                                  ^

C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/BearSSLHelpers.h:154:51: error: expected class-name before '{' token

 class SigningVerifier : public UpdaterVerifyClass {

                                                   ^

C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/BearSSLHelpers.h:157:25: error: 'UpdaterHashClass' has not been declared

     virtual bool verify(UpdaterHashClass *hash, const void *signature, uint32_t signatureLen) override;

                         ^

C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/BearSSLHelpers.h:156:22: error: 'virtual uint32_t BearSSL::SigningVerifier::length()' marked override, but does not override

     virtual uint32_t length() override;

                      ^

C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src/BearSSLHelpers.h:157:18: error: 'virtual bool BearSSL::SigningVerifier::verify(int*, const void*, uint32_t)' marked override, but does not override

     virtual bool verify(UpdaterHashClass *hash, const void *signature, uint32_t signatureLen) override;

                  ^
`

**Comment by gilmaimon** [comment]
There is logical and actual template for bug reports and such issues, throwing the whole error log in an issue is... Well, let's say not great.

Please let me know exactly what code you are trying to compile, what library version you use and what platform libraries version you use. Make sure all of those are up to date..

**Comment by GreenMine** [comment]
Sorry, i found a answer(all answers in close issue:D)
