### ISSUE TITLE
Define protocol

### ISSUE THREAD

**Issue by giorgio80** [gilmaimon/ArduinoWebsockets#62]
Hello, 

I would need to setup a custom protocol name.  Is this possible ? looks like this parameter is not exposed

**Comment by gilmaimon** [comment]
Hi, interesting question. 

It is not supported exactly, but there is a `addHeader` method. You could try setting that header manually if all you need is a protocol name.
Note that if that protocol name change anything with the stracture of messages, the library might not work correctly.

Gil.

**Comment by gilmaimon** [comment]
Did it work?

**Comment by gilmaimon** [comment]
Closing
