### ISSUE TITLE
How to determine the version of the library ?

### ISSUE THREAD

**Issue by denden4444** [gilmaimon/ArduinoWebsockets#63]
Hi Gil 

Happy new year :-)

I would like to know how to determine the version of the library I have installed. 

Is there a way of doing this ? 
Is it possible this can be done at esp boot time and to have it report in serial monitor in a similar way to the
```Is server live? 1```
check ?

Kind regards 
Den

**Comment by gilmaimon** [comment]
Hi @denden4444, happy new year!

There is no way for doing that currently. I tried to add `#define`s for that in the past, but it just was an extra thing for me to maintain, and I always forgot to increment it.

Gil.

**Comment by denden4444** [comment]
Hi Gil ..

Good to hear form you .. trust all is well and thanks for the new years wishes too :-)

Any possibility of a short serial message identifier that's pulled from a particular marker in one of the main files that would get updates in each release ? 
Is there maybe a comments area where you tag each update ? 

If not , no problem I will add one on the next update I make .. just not sure which version I am currently running ;-) 

Kind regards

Den

**Comment by denden4444** [comment]
Gil 

Don't worry I found the version I currently have 0.4.13 installed .. will add a Serial.println in at the start of code or similar.

Thanks again :-) 

Den

**Comment by gilmaimon** [comment]
Glad to hear, enjoy 😄 

Gil.
