### ISSUE TITLE
get messages from the server

### ISSUE THREAD

**Issue by ricpar123** [gilmaimon/ArduinoWebsockets#66]
Hi, I have some troubles with getting msg from the server. From ESP8266 to server is not problem, but whem the server send a msg to ESP it didn't catch.
My server is nodejs + websocket version 7.2.1. here is the part of the code
....
const WebSocket = require('ws');
const s = new WebSocket.Server({ server });
s.on('connection',function(ws,req){
	const ip = req.connection.remoteAddress;
        console.log("new client connected with ip: ", ip);

        /******* when server receives messsage from client trigger function with argument message *****/
        ws.on('message',function(message){
        console.log("Received: "+message); // up to here, all is working!!

        ws.send('Hello from the server'); // this line is not working

ESP8266 code ....

bool connected = client.connect(websockets_server_host, port, "/");
  if(connected) {
    Serial.println("Connected!!");
    client.send("hello server"); // this is print on the server console..ok!!
  }else{
    Serial.println("Not connected");
  } // up to here all is working !!!

client.onMessage([&](WebsocketsMessage message) {
        Serial.print("Got Message: ");
        Serial.println(message.data());
    }); //not working, nothing is printed.

What i am doing wrong?
Thanks

**Comment by gilmaimon** [comment]
Hi, 
First you noticed that your issue is not very well formatted, so the code isn't very easy to read. Anyways, seems like you only shared the `setup` code, do you call `client.poll()` in your `loop` function?

**Comment by ricpar123** [comment]
Thanks for your reply. Well, I would try to send again the code, part of it. 
Server Side.
`const WebSocket = require('ws');
const s = new WebSocket.Server({ server });
 s.on('connection',function(ws,req){
	const ip = req.connection.remoteAddress;
        console.log("new client connected with ip: ", ip);
up to here, all is ok, the ip of ESP8266(client) is getting and printed.

 ws.on('message',function(message){
        console.log("Received: "+message); // this part is also ok. Client send a message "Connected" and this message is getting and printed on the server console.

This part is not ok...Server send a message...
ws.on('open', () => {
		ws.send("Hi greetings from the server");
		});

and is picked by the client....

client.onMessage([&](WebsocketsMessage message) {
        Serial.print("Got Message: ");
        Serial.println(message.data());
    }); // this part is in the setup 

and the loop is like the example..
if(client.available()) {
        client.poll();
    }

The message from the server is not receive by the client.

Regards,




 `

**Comment by gilmaimon** [comment]
I formatted your comment. 
Try setting up `client.onMessage` before calling `client.connect`

**Comment by ricpar123** [comment]
Hello,
 try it, same results.

**Comment by gilmaimon** [comment]
Attach the full Arduino code please, you might be missing something.

**Comment by ricpar123** [comment]
Hi, attach You will find the arduino code and also a printscreen of the
results. Also I send you the server code.
Thank you very much for your kind attention!
Best regards,

Ricardo Caballero

**Comment by gilmaimon** [comment]
Hi, I can't see the attachments. Post the code here in text or share a pastebin link please.

**Comment by ricpar123** [comment]
Ok, let's try again,


Server side:

/**************************websocket_example.js*************************************************/
var bodyParser = require("body-parser");
const express = require('express'); //express framework to have a higher
level of methods
const app = express(); //assign app variable the express class/method
const mongoose = require('mongoose');
var http = require('http');
var path = require("path");
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
const server = http.createServer(app);//create a server
const Registro = require('./modelos/registro');
const Consumo = require('./modelos/watt');

/**********************websocket
setup**************************************************************************************/
//var expressWs = require('express-ws')(app,server);
const WebSocket = require('ws');
const s = new WebSocket.Server({ server });
//when browser sends get request, send html file to browser
// viewed at http://localhost:3000
app.get('/', function(req, res) {
res.sendFile(path.join(__dirname + '/index.html'));
});

//*************************************************************************************************************************
//***************************ws chat
server********************************************************************************

    s.on('connection',function(ws,req){
const ip = req.connection.remoteAddress;
        console.log("new client connected with ip: ", ip);

        /******* when server receives messsage from client trigger function
with argument message *****/
        ws.on('message',function(message){
        console.log("Received: "+message);

/*

var circuito = message.substr(0,3);
        var valor = message.substr(4, 6);
        var vfloat = parseFloat(valor);
        console.log("circuito: ", circuito);
        console.log("energia: ", valor);
        console.log('valor numerico: ', vfloat);

        let watt = new Consumo({
            nombre: circuito,
            valor: vfloat
        });

        watt.save((err, wattDB) => {
            if(err) return err;
            return console.log(wattDB);
        });

        */
        });

ws.on('open', () => {
ws.send("Hola saludos desde el server");
});

            ws.on('close', function(){
                console.log("lost one client");
            });
        //ws.send("new client connected");


    });
        server.listen(3000);
        console.log("servidor conectado en puerto: 3000");

        mongoose.connect('mongodb://localhost:27017/energia',
{useNewUrlParser: true, useUnifiedTopology: true}, ( err, res) => {

                if( err ) throw err;

               console.log("Base de datos ONLINE");

        });



Arduino side:


#include <ESP8266WiFi.h>
#include <ArduinoWebsockets.h>




const char* ssid     = "softFree";
const char* password = "458223**";

const char* websockets_server_host = "192.168.100.6";
const uint16_t port = 3000;


using namespace websockets;

WebsocketsClient client;


void setup() {
 Serial.begin(115200);
 connect_wifi();
  delay(10);

  connect_socket();
  delay(10);

}

void loop() {

if(client.available()) {
  client.poll();
}


  delay(1000);
}



void connect_wifi(){

  Serial.println();
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());

}

void connect_socket(){

  client.onMessage([&](WebsocketsMessage message) {
        Serial.print("Got Message: ");
        Serial.println(message.data());
    });

  bool connected = client.connect(websockets_server_host, port, "/");
  if(connected) {
    Serial.println("Client Connected!!");
    client.send("hello server");
  }else{
    Serial.println("Not connected");
  }
}

**Comment by gilmaimon** [comment]
Hi, I don't see anything wrong with the client code... Maybe try an online client (there are many chrome extensions) and see if everything works fine there?

**Comment by ricpar123** [comment]
Hi, finally I found the error, it was on the server side. Now, everything works fine!
Thanks for your suppport!

**Comment by atmoner** [comment]
> Hi, finally I found the error, it was on the server side. Now, everything works fine!
> Thanks for your suppport!

A little additional clue? 
I am trying to send a request from ArduinoWebsockets to a ws nodejs server

My ws server nodeJs:
```
const WebSocket = require('ws');
const wss = new WebSocket.Server({ port: 8050 });

wss.on('connection', function connection(ws) {
	ws.on('message', function incoming(message) {
		console.log('received: %s', message);
	});
	
	ws.send('something-server');
});
```

No response ever reaches the server:

**Comment by gilmaimon** [comment]
Hi @atmoner! Open a new issue and I'll do my best to help you there! It's kinda hard to manage it here in an already closed issue :)

Gil.
