### ISSUE TITLE
Connection problem to Toggl's Secure Web Socket

### ISSUE THREAD

**Issue by imesut** [gilmaimon/ArduinoWebsockets#67]
**Describe the bug**
Hello,

I see a connection problem for **wss://stream.toggl.com/ws** link.

This link receives authentication token then decides to continue or disconnect. But in every attempt, it disconnects immediately before sending token.

The patch metnioned at [Issue 9](https://github.com/gilmaimon/ArduinoWebsockets/issues/9) didn't worked for me. Any suggestions?

**To Reproduce**
The problem can be repeated with any version of the library.
I'm using Lolin Node MCU with ESP8266. 

**Logs**
```
BSSL:Connected!
BSSL:read: failed
BSSL:read: failed
Also multiple times:
BSSL:read: failed
BSSL:read: failed

After some logs:
Connnection Closed
```

**Comment by gilmaimon** [comment]
Thanks, I'll look into it. Can you also provide the relevant code you are using?

**Comment by gilmaimon** [comment]
Hi @imesut , thank you for pointing out the issue.
This seems like a problem with the http headers sent by the library, it seems like your server requires `Origin` header, which is not present currently. I added it and uploaded a patch (version [0.4.15](https://github.com/gilmaimon/ArduinoWebsockets/releases/tag/0.4.15)). It should be in the Library Manager (in the Arduino IDE) soon, but you can clone master right now and it should work.

Please let me know if everything works for you as expected 👍 

Thanks, 
Gil.

**Comment by imesut** [comment]
Thanks, it works!
