### ISSUE TITLE
Sending two sets of data in the same connection

### ISSUE THREAD

**Issue by xgarb** [gilmaimon/ArduinoWebsockets#7]
Me again. As part of the same set of projects I'm using face detection and recognition from this library: https://github.com/espressif/esp-who

I want to send images and also a message to the browser (for further actions) when a face is detected. I can do it like this which is working well:

```
(loop)
   //camera and detection stuff here
    if(detected==true){
      client.send("Face Detected");
      }
    client.sendBinary((const char *)_jpg_buf, _jpg_buf_len);
(/loop)
```

```
		ws.onmessage = message => {
                  if (typeof message.data === 'string'){
                    console.log("Face Detected")
                  }
                  if (message.data instanceof Blob){
		     var urlObject = URL.createObjectURL(message.data);
		     ws_img.setAttribute('src', urlObject);
                  }
```

I'm not sure this is the best way to separate the two sent items. Also if I can work out how to do it I want to send the mapping of the face instead of just a message which I'm guessing will be another blob.

Is this the best way of sending two different things to the client? I couldn't see a way of identifying messages as they are sent.

I'll get back to you on the other question soon.

**Comment by gilmaimon** [comment]
This is more of a general programming queshtion, but I am happy to try and help. 

Your solution is fine, but it will be a bit hard to extend in the future.

The Websockets protocol defined 2 types of data messages: Binary and Text (UTF8). You could look up the docs on the library you are using on the PC and check what is the method name that checks if a message is binary or text.

A more general approach, is to define some kind of protocol of your own. For example, you could say that **before every message you send a text messages that represent the type of data being sent next**. For example, Esp code:
```c++
if(...) {
   client.send("DETECTION");
   client.sendBinary("Face Detected");
}
client.send("IMAGE");
client.sendBinary((const char *)_jpg_buf, _jpg_buf_len);
```

Then, on the other side you will accept a message, and use `switch` or `if-else`s to act depending on the data you know you are about to get next. 

This protocol is not very slim or efficient, but you can apply the general concept however you like :)

Btw, is sending the images working well for you?

**Comment by xgarb** [comment]
Thanks for the advice. Sending images seems to work well at lower resolutions but the WiFi disconnects on the ESP at high resolutions. I'm going to do more testing on streaming the camera output using websockets vs the JPEG HTTP Stream method used here: https://github.com/espressif/esp32-camera/tree/master

**Comment by gilmaimon** [comment]
Interesting. You can try using streaming with this library. See this https://github.com/gilmaimon/TinyWebsockets/wiki/Client#Streaming---Sending-Fragmented-Messages

**Comment by gilmaimon** [comment]
Hi, can I close the issue?

**Comment by xgarb** [comment]
I'm working on another project that I want to test with this library as an alternative. Hopefully today!
