### ISSUE TITLE
::connect / raw socket / handshake / protocol error

### ISSUE THREAD

**Issue by r2d2r01** [gilmaimon/ArduinoWebsockets#70]
So bravo for library.
I try to connect to a socket server in php but it starts communication by a connect() ... which execute a generateHandshake(). If answer is not "HTTP/1.1..." i receive a protocol error reason. Fine, but how I can send in raw data without protocol http  (I can't customize the php code server) which don't supports http, just a listen socket ? 
I'm looking to use directly raw socket or comment this piece of code / rewrite a connect() ..
Thank's for answer
Regards
Frederic
PS: sorry if it's bad request section

**Comment by gilmaimon** [comment]
Hi, websockets as a protocol is upgraded from an http connection. If you are looking for raw tcp sockets, this is not it. You might be looking for WiFiClient or any Arduino http client (if you are looking for http libraries.

Gil.

**Comment by r2d2r01** [comment]
Hi, in effect,  i use esp directly & some librairies for socket. I was looking for use one rather than some others which encapsulate "same" functions but certains best writted or not present. After analyse your code i remark Your library is very atractive for certificate/secure connection, for symetric crypt and raw socket i will use native esp lib. 
Thank's a lot
Frederic
