### ISSUE TITLE
Allow Client certificate and key for verification

### ISSUE THREAD

**Issue by jjcarstens** [gilmaimon/ArduinoWebsockets#72]
I'm trying to work in an environment that uses Client-side SSL. I want to try uses some ESP32's and connect to the services with them via websockets.

This would require being able to specify a client certificate and client key along with the CA certs. Is that something that this library can do or _would_ want to do?

I've done a bit of digging, but my Websocket knowledge is just a little lacking to know if this is a reasonable feature request

**Comment by gilmaimon** [comment]
Approved
