### ISSUE TITLE
Not Connected!

### ISSUE THREAD

**Issue by sachinbaghel14** [gilmaimon/ArduinoWebsockets#73]
Not working please help. i have deployed my server to heroku written in node.js and i am trying to connect to that.

**In arduino console-**
15:48:41.262 ->
15:48:41.262 -> v951aeffa
15:48:41.262 -> ~ld
15:48:41.297 -> ...Connected to Wifi, Connecting to server.
15:48:49.319 -> Not Connected!

**here is my client code-**

/*
Esp8266 Websockets Client

This sketch:
    1. Connects to a WiFi network
    2. Connects to a Websockets server
    3. Sends the websockets server a message ("Hello Server")
    4. Prints all incoming messages while the connection is open

Hardware:
    For this sketch you only need an ESP8266 board.

Created 15/02/2019
By Gil Maimon
https://github.com/gilmaimon/ArduinoWebsockets
*/

#include <ArduinoWebsockets.h>
#include <ESP8266WiFi.h>

const char* ssid = "Aqua Craze11"; //Enter SSID
const char* password = "0987654321"; //Enter Password
const char* websockets_server_host = "https://secure-mountain-02060.herokuapp.com"; //Enter server adress
const uint16_t websockets_server_port = 8080; // Enter server port

using namespace websockets;

WebsocketsClient client;
void setup() {
Serial.begin(115200);
// Connect to wifi
WiFi.begin(ssid, password);

// Wait some time to connect to wifi
for(int i = 0; i < 10 && WiFi.status() != WL_CONNECTED; i++) {
    Serial.print(".");
    delay(1000);
}

// Check if connected to wifi
if(WiFi.status() != WL_CONNECTED) {
    Serial.println("No Wifi!");
    return;
}

Serial.println("Connected to Wifi, Connecting to server.");
// try to connect to Websockets server
bool connected = client.connect(websockets_server_host, websockets_server_port, "/");
if(connected) {
    Serial.println("Connecetd!");
    client.send("Hello Server");
} else {
    Serial.println("Not Connected!");
}

// run callback when messages are received
client.onMessage([&](WebsocketsMessage message) {
    Serial.print("Got Message: ");
    Serial.println(message.data());
});
}

void loop() {
// let the websockets client check for incoming messages
if(client.available()) {
client.poll();
}
delay(500);
}

**this is the server code written in node.js-**

const websocket = require('ws').Server;

const wss = new websocket({port:process.env.PORT || 8081});
console.log(prt);

wss.on('connection', function(socket){

console.log("new Client Connected");

socket.on('message', function(){
wss.clients.forEach(function each(client){
client.send('data')
})
});

socket.on('close', function(){
console.log('client closed');
});

});

const brodcast = function(){
wss.clients.forEach(function each(client){
client.send('data')
})
}

setInterval(brodcast, 1000);

**Comment by gilmaimon** [comment]
Many issues here:
- First, take some time to format your code so it is easier to read
- Second, you are trying to connect on port 8080, but is your server running on 8080? (hint: no, it's on 80)
- Third, you are connecting to "https://..." but is your server using ssl? (hint again: no, its using plain http)

Try connecting to your server from a normal client first (there are some nice websocket client chrome extensions) and then you will understand what is wrong with the code.

Good luck!
