### ISSUE TITLE
Connect error at Secured-Esp8266-Client.ino

### ISSUE THREAD

**Issue by matsujirushi** [gilmaimon/ArduinoWebsockets#8]
I got 'false' at client.connect().
[here](https://github.com/gilmaimon/ArduinoWebsockets/blob/master/examples/Secured-Esp8266-Client/Secured-Esp8266-Client.ino#L77)

Maybe wss://echo.websocket.org/ is changed [fingerprint](https://github.com/gilmaimon/ArduinoWebsockets/blob/master/examples/Secured-Esp8266-Client/Secured-Esp8266-Client.ino#L34).

**Comment by gilmaimon** [comment]
I will check it out this weekend and will upload an updated example.
Thank you!

**Comment by gilmaimon** [comment]
Thank you @matsujirushi, I've updated the fingerprint 👍 
For future reference, the command I ussed was:
```
openssl s_client -connect echo.websocket.org:443 | openssl x509 -fingerprint -noout
```

Thank you.

**Comment by matsujirushi** [comment]
Thanks for great support !
