### ISSUE TITLE
Compilation error with esp8622 esp-01 

### ISSUE THREAD

**Issue by Androz2091** [gilmaimon/ArduinoWebsockets#81]
**Describe the bug**
Hello,
I'm getting the following error:
```
In file included from /Users/simon/Documents/Arduino/libraries/ArduinoWebsockets/src/tiny_websockets/message.hpp:3:0,
                 from /Users/simon/Documents/Arduino/libraries/ArduinoWebsockets/src/ArduinoWebsockets.h:4,
                 from /Users/simon/Documents/GitHub/arduino-discord/arduino-discord.ino:7:
/Users/simon/Documents/Arduino/libraries/ArduinoWebsockets/src/tiny_websockets/internals/ws_common.hpp:4:10: fatal error: string: No such file or directory
 #include <string>
          ^~~~~~~~
compilation terminated.
exit status 1
```

**To Reproduce**

I'm using ArduinoWebsockets v0.4.17.
I'm using a Arduino Uno card, with an Esp8266 esp-01 wifi module plugged on it.

**Expected behavior**

I'm getting an error when I try to upload the code to the card.

**Code**
```cpp
#include <ArduinoWebsockets.h>

void setup() {
    Serial.begin(115200);
}

void loop() {
}
```

**Additional context**

I think it's because this is not compatible with Arduino Uno, but as I have an esp8266 wifi module it should work...

**Comment by gilmaimon** [comment]
Hi,

This library uses the STL which is available by default with the esp8266 and esp32 boards environment in the Arduino IDE.
Arduino UNO does not have those stuff available, you could try to install some arduino STL library and adapt the library code, but out-of-the-box, this library only supports esp8266 and esp32 boards (as mentioned in the README).

Gil.

**Comment by Androz2091** [comment]
Thank you, I used an esp8266 board to make [this](https://github.com/Androz2091/arduino-is-mybot-online), but I will look into STL library because a lot of people only have an Arduino Uno with a simple wifi module.
