### ISSUE TITLE
Not connecting to WSS Server

### ISSUE THREAD

**Issue by Damilare1** [gilmaimon/ArduinoWebsockets#83]
Hi, I'm trying to connect to a WSS server using a custom library I built for the ESP32 module. I followed the instructions in the readme, but I can't seem to get it to connect or troubleshoot the errors. I may need some guidance here as I'm not that experienced.

I am using the Arduino websocket server 0.4.17
The WebsocketServer URL is "wss://ws.finnhub.io?token=xxxxxxxxx" (you'll have to generate a free token on the website at finnhub.io).

The Websocket client was declared in the library class called Stock

```
private:
    unsigned long _baudRate;

public:
    WebsocketsClient client;

public:
    int responseCode;

```

The object is instantiated, the pins are initialized and the client attempts to connect to the WSS server after the WiFi connects successfully.

```
String serverPath = apiUrl + token;

Stock TSLA(OUTPUT26, OUTPUT27, baud, onMessageCallback, onEventsCallback, serverPath);

void setup() {
  //Call init function to initialise the pins in order to allow time for the hardware to settle to a stable state before being used.
    TSLA.init();
  WiFi.begin(ssid, password);
  Serial.println("Connecting");
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.print("Connected to WiFi network with IP Address: ");
  Serial.println(WiFi.localIP());
    TSLA.client.connect(serverPath);
}
```

I think this is suppose to check for updates from the server...
````
void loop() {
  //Send an HTTP POST request every 10 minutes
  if ((millis() - lastTime) > timerDelay) {
    //Check WiFi connection status
    if (WiFi.status() == WL_CONNECTED) {
      Serial.print(TSLA.client.available());
      Serial.print(TSLA.connected);
        TSLA.client.poll();
    }
    else {
      Serial.println("WiFi Disconnected");
    }
    lastTime = millis();
  }
}
````

The issue is that TSLA.client.available returns 0 and TSLA.client.connected also has a value of 0

**Comment by gilmaimon** [comment]
Hi,

What's the value of `apiUrl `?

Gil

**Comment by Damilare1** [comment]
The link is: wss://ws.finnhub.io?token=broje7frh5r8qo23b82g

**Comment by gilmaimon** [comment]
Can you try using the examples and just use this url instead what is provided in the example? Does it work there? If it does, it might be an error in your usage rather than a bug in the library.

Also, can you try printing the error code (reason) like documented here: https://github.com/gilmaimon/TinyWebsockets/wiki/Client#Close-Reason-Codes. It might help understanding the reason it does not work.  It's also important to check the return value of `client.connect`...

Another thing which might help is looking at the esp logs (set level to verbose), does it say anything interesting?

**Comment by Damilare1** [comment]
` hostByName(): DNS Failed for ws.finnhub.io?token=b`

This has to be where the error is from. I noticed the wss protocol was stripped from the URL, please how do I interact with a secure websocket api?

**Comment by gilmaimon** [comment]
Hmm.. seems like the library is having trouble noticing that `?token...` is actually not part of the host name, Try using this url:
```cpp
"wss://ws.finnhub.io/?token=broje7frh5r8qo23b82g"
```
Notice the added `/` to signal that the path ends there. Did it work?

**Comment by Damilare1** [comment]
Amazing it works now, thanks so much!

**Comment by dezur** [comment]
Same problem here. Cannot connect to:

wss://ws.coincap.io/prices?assets=bitcoin,ethereum

**Comment by Damilare1** [comment]
You can try `"wss://ws.coincap.io/prices/?assets=bitcoin,ethereum"`

**Comment by dezur** [comment]
> Can try you `"wss://ws.coincap.io/prices/?assets=bitcoin,ethereum"`. Seems the library may be having trouble noticing the assets query

Tried with no luck... :(
Connecting to another wss server works fine but this one doesn't.

**Comment by Damilare1** [comment]
It appears the endpoint has some security issues. I tried connecting to the socket from Chrome. Got this error and no response:
<img width="1559" alt="Screen Shot 2021-01-04 at 9 54 10 PM" src="https://user-images.githubusercontent.com/29501113/103578877-9df5d100-4ed7-11eb-85aa-cda10ae0ae68.png">

You'll probably find something similar if you look into the esp logs (set level to verbose)

**Comment by dezur** [comment]
Strange!.. For me it works fine with Simple Websocket Client extension to chrome.
![image](https://user-images.githubusercontent.com/46935887/103579787-3fc9ed80-4ed9-11eb-8cfd-9469510550e3.png)

I also had success in java...

**Comment by jandebleser** [comment]
Seems to me the library expects the / to be there before the ?, but the server does not allow the / to be at the end of the url. 
Either the server needs to allow it, or the client code needs to be fixed (better).
