### ISSUE TITLE
how i can connect websocket client with token in header to server (ESP8266)

### ISSUE THREAD

**Issue by sachinbaghel14** [gilmaimon/ArduinoWebsockets#87]
In my ESP8266 application, i would like to connect web socket server, but while connecting i need to send token (already generated JSON token) in header. When i tried to connect without token it will diffuse connection. Please suggest me any solution so I can connect my esp8266 with websocket server (How i can add token in header of websocket client)

Please suggest any example program.

**Comment by gilmaimon** [comment]
If you need to add a new header you can use `addHeader` on your client. 

If you need to pass it as a GET parameter you can just add `/?key=value` to your url.

**Comment by sachinbaghel14** [comment]
can you tell me how can i use addHeader and where should i use it. I am trying to implement it on Esp8266-Client expample

**Comment by gilmaimon** [comment]
Before you call `client.connect(..)`, call `client.addHeader(key, value)`

**Comment by sachinbaghel14** [comment]
okk thankyou 👍
