### ISSUE TITLE
(WS Client) Get close code sent by the server

### ISSUE THREAD

**Issue by Androz2091** [gilmaimon/ArduinoWebsockets#98]
**Is your feature request related to a problem? Please describe.**

I'd like to retrieve the close code sent by the server when it closes the connection (4000, 4001, etc.).

**Describe the solution you'd like**

```cpp
void onEventsCallback(WebsocketsEvent event, String data) {
    if(event == WebsocketsEvent::ConnectionOpened) {
        Serial.println("Websocket Connnection Opened!");
        Serial.println(data);
    } else if(event == WebsocketsEvent::ConnectionClosed) {
        Serial.println("Websocket Connnection Closed!");
        Serial.println(data); // here data is an empty string. I think that it should be the close code
    }
}
```

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by gilmaimon** [comment]
Hi! 

Seems like it was missing from the wiki, so I updated it. Look here: https://github.com/gilmaimon/TinyWebsockets/wiki/Client#Close-Reason-Codes

In short, you can call `client.getCloseReason()` :)

**Comment by Androz2091** [comment]
Thank you so much 👍 
It worked! By the way, I was getting 1006 error instead of 4013... Is there any error in the handling of the codes? (it could be a problem on the websocket server side, so don't worry if you think everything is correct)
*And usage question label has a typo error 🙃*
